name: My First Workflow
on: push
jobs:
    first-job:
        runs-on: ubuntu-latest
        steps: 
        - name: Checkout
          uses: actions/checkout@v4
        - name: Multiline commands
          run: |
            echo "hello world"
            ls -ltra
            cat README.md

        - name: Execute Shell Script
          run: |
            chmod +x ./ascii-script.sh
            ./ascii-script.sh



        # - name: Welcome Message
        #   run: echo "hello world"
        # - name: List Files
        #   run: ls
        # - name: Read File
        #   run: cat README.md
            